# Setup

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
#Qn So formula is a module and api is a submodule within the formula submodule?
#Qn What is the difference between the 2 lines before

cols = ['ORings', 'DistressedOrings', 'Temp', 'Pressure', 'TempOrderOfFlight']

df = pd.read_csv('module09/o-ring-erosion-or-blowby.csv', names=cols)

df

    ORings  DistressedOrings  Temp  Pressure  TempOrderOfFlight
0        6                 0    66        50                  1
1        6                 1    70        50                  2
2        6                 0    69        50                  3
3        6                 0    68        50                  4
4        6                 0    67        50                  5
5        6                 0    72        50                  6
6        6                 0    73       100                  7
7        6                 0    70       100                  8
8        6                 1    57       200                  9
9        6                 1    63       200                 10
10       6                 1    70       200                 11
11       6                 0    78       200                 12
12       6                 0    67       200                 13
13       6                 2    53       200                 14
14       6                 0    67       200                 15
15       6                 0    75       200                 16
16       6                 0    70       200                 17
17       6                 0    81       200                 18
18       6                 0    76       200                 19
19       6                 0    79       200                 20
20       6                 2    75       200                 21
21       6                 0    76       200                 22
22       6                 1    58       200                 23